### PR TITLE
Feature/non op build 29

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
While preparing the tag for GFS 16.3 an attempt was made to prune all code/scripts not designed to be included in operations. Once those sections were pruned though the build failed because cmake was unable to find some of the pruned subdirectories.

This change adds a BUILD_ONLY_FOR_NCO build option to the top level CMakeList.txt file.  When this option is set to ON only those subdirectories intended to be used in operations are included in the build and all other subdirectories are ignored.  The default setting is OFF.

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]
I have no issue with the changes themselves, but where do those directories come from when you're not building for NCO?

**Comment by EdwardSafford-NOAA** [comment]
@WalterKolczynski-NOAA The directories are in GSI-monitor.  Each of the monitors has an nwprod directory which contains things intended for use in ops.  The other directories contain scripts and executables intended to run in developer space not ops -- plotting and utility functions.  The idea was to enable cmake to not choke on missing subdirectories and at the same time provide some indication of what was intended for ops and what was not.

**Comment by aerorahul** [comment]
@EdwardSafford-NOAA 
I think we can do better than pruning in a cloned space.  That leaves a "dirty" cloned directory.
When we create the NCO tag, we should remove the directories that NCO does not want from the release branch, and then create the tag.

**Comment by WalterKolczynski-NOAA** [comment]
> @EdwardSafford-NOAA I think we can do better than pruning in a cloned space. That leaves a "dirty" cloned directory. When we create the NCO tag, we should remove the directories that NCO does not want from the release branch, and then create the tag.

I dislike even doing that. It alienates the release branch from develop and complicates things if you need to test the release branch or bring commits back from it.

**Comment by EdwardSafford-NOAA** [comment]
> @EdwardSafford-NOAA I think we can do better than pruning in a cloned space. That leaves a "dirty" cloned directory. When we create the NCO tag, we should remove the directories that NCO does not want from the release branch, and then create the tag.

My understanding, per @RussTreadon-NOAA , is that is what took place.  I haven't been directly involved in creating the NCO tag so I can't really speak to that.  What I heard was that, after deleting unneeded GSI-monitor directories, cmake failed.  I was looking to circumvent that in the future.

**Comment by aerorahul** [comment]
> > @EdwardSafford-NOAA I think we can do better than pruning in a cloned space. That leaves a "dirty" cloned directory. When we create the NCO tag, we should remove the directories that NCO does not want from the release branch, and then create the tag.
> 
> My understanding, per @RussTreadon-NOAA , is that is what took place. I haven't been directly involved in creating the NCO tag so I can't really speak to that. What I heard was that, after deleting unneeded GSI-monitor directories, cmake failed. I was looking to circumvent that in the future.

You are correct @EdwardSafford-NOAA 
I think for now, we are ok with this approach of pruning.

**Review by aerorahul — APPROVED** [review]

**Pull request merged**
