### PR TITLE
Feature/gwdev issue 2329

### PR DESCRIPTION
**Pull request by HenryRWinterbottom**
This PR adds support for the RDHPCS Rocky-8 upgrade.

Related issue: [#2329](https://github.com/NOAA-EMC/global-workflow/issues/2329)

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
looks good.

**Review by DavidHuber-NOAA — APPROVED** [review]
I've tested the ozone and radiance monitors in a global-workflow test.  The minimization monitor needs a Perl module (Lists/MoreUtils) in order to be testable from the workflow.  Since that module is only required for the global workflow: approve.

**Review by EdwardSafford-NOAA — APPROVED** [review]
Good by me.

**Comment by DavidHuber-NOAA** [comment]
The Hera GNU module file should also be updated.

**Pull request merged**
