### PR TITLE
Ref #12

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
Add bacio to common.lua, rm wcoss_dell/cray in machine/module setup.

### CODE REVIEW

**Comment by EdwardSafford-NOAA** [comment]
Updated common.lua module to use bacio/4.2.1 and w3emc/2.9.2, removed references to wcoss_dell and cray.  Builds without issue on wcoss2, hera, and orion.

**Comment by EdwardSafford-NOAA** [comment]
@aerorahul I think the review request for this PR got lost.  Please take a look when you have a moment.  Thanks.

**Review by DavidHuber-NOAA — APPROVED** [review]
Builds fine on S4, but fails on Jet.  The changes look good to me and it seems that the Jet modulefile just needs to be updated.  I can tackle that in a separate issue.

**Review by aerorahul — APPROVED** [review]
This looks good.
Only one thing that I would think of is in `ci/spack.yaml` to add `bacio/2.4.1` as a dependency.
It doesn't really matter because spack will find the dependencies automatically.

**Comment by aerorahul** [comment]
@EdwardSafford-NOAA Sorry for the delay.  I was on leave last week.

**Comment by EdwardSafford-NOAA** [comment]
@DavidHuber-NOAA  Thanks very much.  I'll open a new issue for builds on Jet.

**Pull request merged**
