### PR TITLE
update orion modulefile for rocky8 upgrade

### PR DESCRIPTION
**Pull request by aerorahul**
As the title suggests.

Tested the build on Orion.

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
Same suggestion as for gfs-utils.  Change

https://github.com/NOAA-EMC/GSI-Monitor/blob/37fbc100aeb298ae6434910f897e43d1dd31f94c/ush/detect_machine.sh#L78-L83

to
```bash
 elif [[ -d /work ]]; then 
  mount=$(findmnt -n -o SOURCE /home)
  if [[ ${mount} =~ "hercules" ]]; then
    MACHINE_ID=hercules
  else
    MACHINE_ID=orion
  fi
```

**Review by EdwardSafford-NOAA — APPROVED** [review]
Looks good to me.

**Review by DavidHuber-NOAA — APPROVED** [review]
Looks good!

**Comment by DavidHuber-NOAA** [comment]
GitHub PR and action  are running in a degraded mode according to https://www.githubstatus.com/.

**Pull request merged**
