### PR TITLE
Update module files to build gsi_monitor on Gaea-C5

### PR DESCRIPTION
**Pull request by DavidBurrows-NCO**
Update module files to build gsi_monitor on Gaea-C5
add modulefiles/gaea.intel.lua
modify ush/module-setup.sh

Ref #138 
Cross Ref NOAA-EMC/global-workflow/issues/2535

### CODE REVIEW

**Comment by DavidBurrows-NCO** [comment]
Hello...I just added a gaea.intel-run.lua to the module files. Is there a way to test the gsi_monitor? So far I have built it and test loaded the gaea.intel-run.lua file on Gaea.  Thanks!

**Comment by DavidBurrows-NCO** [comment]
Hi, @EdwardSafford-NOAA. I just wanted to check in on this PR and see if anyone had a chance to take a look. I've reached out to you since this is a similar #136 that you merged with Wei. Let me know if I should tag someone else.  Thanks!

**Comment by EdwardSafford-NOAA** [comment]
@DavidBurrows-NCO Sorry, hadn't spotted this PR.  I've started the ci tests and will look it over this morning.  Thanks!

**Review by EdwardSafford-NOAA — APPROVED** [review]
Looks good.  Thanks.

**Comment by DavidBurrows-NCO** [comment]
Excellent. Thanks @EdwardSafford-NOAA for getting back to me so quickly this AM.

**Pull request merged**
