### PR TITLE
Upgrade to spack-stack modules on non-production machines

### LINKED ISSUE #98: Use EPIC-managed spack-stack installations for non-production machines
The UFS has migrated to spack-stack/1.4.1 and there is work being done to migrate the GSI to the same (https://github.com/NOAA-EMC/GSI/issues/589) on non-production machines (WCOSS2 is still using Intel/19). The GSI-monitor repository should also be migrated to use spack-stack. This will involve a few upgrades at once: Intel 18 to 2021+, hdf5/1.10.6 to 1.14.0, and netcdf/4.7.4 to 4.9.2. 

I am going to try this in one step to bypass #80 (since hpc-stack is minimally supported) and address #88.  My suggested plan for testing is to run 40 cycles in the global workflow and also manually run each of the monitors on the output data, comparing output and plots against the Intel 18 versions.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
This upgrades modules to spack-stack-built libraries for all non-production machines.  This has been test build on Hera, Orion, Jet, S4, and WCOSS2 and tested on Hera and Orion in a global workflow cycled experiment.  Standalone tests were not performed.

Resolves #98

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
I'm not sure how to fix the CI error.  During the cmake setup step of the `bacio` library, it states that `ifort` is unable to compile a simple program.  It seems this is a problem with the spack Intel build of the compiler.  Any suggestions @EdwardSafford-NOAA @aerorahul?

**Review by aerorahul — APPROVED** [review]
looks good to me.

**Review by EdwardSafford-NOAA — APPROVED** [review]
Looks good to me, thanks.

**Comment by EdwardSafford-NOAA** [comment]
@DavidHuber-NOAA Sorry for the delay, I was out last week.  Is this good to go now or do you anticipate additional changes?

**Comment by DavidHuber-NOAA** [comment]
No problem, @EdwardSafford-NOAA!  Hope it was a good Thanksgiving!

I tested on all platforms but S4, which @souopgui tested today and I had to make a small change for.  He is rerunning the G-W jobs now.  Once verified, I'm good with merging.

**Comment by DavidHuber-NOAA** [comment]
@EdwardSafford-NOAA This worked on S4, so I think it is ready to merge.

**Comment by EdwardSafford-NOAA** [comment]
@DavidHuber-NOAA Great!  Thanks.

**Pull request merged**
