### PR TITLE
Update ConMon's convinfo file

### LINKED ISSUE #148: Update global_convinfo file
The ConMon's global_convinfo file needs to be updated to reflect recent changes in satwind data sources.

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
Update ConMon's `global_convinfo.txt` file to pull in recent changes to satwinds.  This corrects missing time series data and plots.

Testing has been done on wcoss2, confirming data extraction is now taking place for these data types/subtypes:

- uv244-03
- uv244-05
- uv245-272
- uv246-272
- uv247-272
- uv260-226

Note:  Obs data for uv246 (all subtypes) has ceased as of the 2024110718z cycle.  Whatever the issue it's upstream of the ConMon.

Corresponding website menu changes have been made to make these plots available on the ConMon site.

Closes #148

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
Is this PR supposed to bring `src/Conventional_Monitor/nwprod/gdas_conmon/fix/global_convinfo.txt` in sync with the operational `global_convinfo.txt`?

If "yes", it certainly brings it into closer agreement but some differences remain.

**Comment by EdwardSafford-NOAA** [comment]
Yes, good catch.  I updated `global_convinfo.txt` from my GSI repo on wcoss2 but it was out of date.  (I crossed myself up between machines.)  I've updated the file and will let it run overnight to confirm the next few cycles are handled correctly.  If that goes as expected I'll ask for a re-review tomorrow morning.  Sorry for the false start.

**Review by RussTreadon-NOAA — COMMENTED** [review]
@EdwardSafford-NOAA .  Look good.  The only difference between `src/Conventional_Monitor/nwprod/gdas_conmon/fix/global_convinfo.txt` and gfs.v16.3.19 is 
```
russ.treadon@clogin04:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi_monitor/pr149> diff /lfs/h1/ops/prod/packages/gfs.v16.3.19/fix/fix_
gsi/global_convinfo.txt src/Conventional_Monitor/nwprod/gdas_conmon/fix/global_convinfo.txt
260c260
<  gps      267    0   -1     3.0      0      0      0  10.0  10.0   1.0  10.0  0.000000     0    0.     0.      0    0.     0.    0    0
---
>  gps      267    0    1     3.0      0      0      0  10.0  10.0   1.0  10.0  0.000000     0    0.     0.      0    0.     0.    0    0
```

This may be intentional.  We want to turn on assimilation of PlanetIQ gpsro data.  This is what you have in your `global_convinfo.txt`.

**Comment by EdwardSafford-NOAA** [comment]
Yes, that won't cause any problems within the ConMon.

**Review by RussTreadon-NOAA — APPROVED** [review]
Approve pending confirmation that WCOSS2 testing shows expected / desired behavior.

**Comment by EdwardSafford-NOAA** [comment]
Confirming the data extraction and resulting ConMon plots now show data for the cases above.  

For the record there is one exception which is unrelated to this change.  Case uv246-272 has no data; indeed all uv246 obs (all subtypes) have had zero obs since the 2024110718 cycle.  Brett Hoover has asked the obs proc team to look into that.  From the ConMon side the uv246-* plots are now correctly showing zero obs.  I've been through the cnvstat files manually using ncdump and have confirmed there are no uv246* obs since 2024110718z.

**Comment by RussTreadon-NOAA** [comment]
@EdwardSafford-NOAA , I can merge now or we can wait for additional reviews / testing.  Let me know your preference and we'll go from there.

**Comment by EdwardSafford-NOAA** [comment]
@RussTreadon-NOAA I think it's safe to merge this.

**Pull request merged**
