### PR TITLE
Load hpc-impi module in each <machine.compiler>-run.lua module file.

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
The wgrib2 module is loaded via common-run.lua when any of the <machine.compiler>-run.lua modules are loaded. However, hpc-impi is not loaded, which means a non-hpc-stack module is used. To fix this, hpc-impi should be loaded in each <machine.intel>-run.lua modulefile.

Please note that I made changes to the s4 and jet -run.lua files but the changes are untested.  The changes are consistent with the changes to other files but I don't have access to those machines.

Completes #59.

### CODE REVIEW

**Comment by EdwardSafford-NOAA** [comment]
@DavidHuber-NOAA I think this PR review request got lost along the way.  Can you take a look when you're able.  Thanks.

**Review by DavidHuber-NOAA — APPROVED** [review]
Changes look good.  I've loaded the new modulefiles on Jet and S4 and verified they are correct.  Sorry for the delay.

**Comment by EdwardSafford-NOAA** [comment]
@DavidHuber-NOAA  Thanks and no worries at all.

**Comment by EdwardSafford-NOAA** [comment]
@DavidHuber-NOAA I'm sorry but I think I have to re-request a review.  I updated the branch with the latest develop and while your review still is checked as complete merging isn't an option.  Sorry, I should have updated it first.

**Comment by DavidHuber-NOAA** [comment]
@EdwardSafford-NOAA It was just a draft PR.  I've marked it as ready to review now, so it should be mergeable.

**Comment by EdwardSafford-NOAA** [comment]
Oh jeez.  Need a new prescription for my glasses.  Thanks.

**Pull request merged**
