### PR TITLE
Port to Hercules

### LINKED ISSUE #101: Port to Hercules
The GSI-Monitor should be ported to Hercules to support cycled global workflow experiments.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
This ports the gsi-monitor to Hercules and resolves #101.

Only a test build has been performed at this point.  I will be starting a global workflow cycled experiment shortly, which will test the data extraction programs.  Plotting routines can be run after a few cycles have completed.

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
I am having trouble with the minmon on Hercules.  It seems the MoreUtils library is not installed on the system, which is required by `global-workflow/ush/minmon_xtrct_gnorms.pl`.  I have requested that this library be installed.

**Comment by DavidHuber-NOAA** [comment]
@EdwardSafford-NOAA I am requesting a number of Perl modules to be installed on Hercules that appear to be used in gsi-monitor:

```
List::MoreUtils
Date::Calc
FileHandle
Arch_utils
FindBin
Manipulate_time
Math::Trig
Recd_State
Remote_utils
Time::JulianDay
XML::LibXML
XML::Simple
```

Do you know if any of these are no longer needed?

**Comment by EdwardSafford-NOAA** [comment]
The only ones on the list that I can confirm are still used in gsi-monitor are:
`List::MoreUtils`
`Date::Calc`
`Math::Trig`

The two XML modules and FileHandle I recognize as once having been used, but the rest are not familiar to me at all.

**Comment by DavidHuber-NOAA** [comment]
Following the installation of the required Perl modules during the last maintenance period on Hercules, I have tested this out within the global workflow on Hercules and it works for data generation.

**Review by EdwardSafford-NOAA — APPROVED** [review]
Looks good to me.  Thanks for working on this!

**Pull request merged**
