### PR TITLE
Add/fix build capability for Gaea-C5, Gaea-C6, and container

### LINKED ISSUE #145: Add/fix build capability for Gaea-C5, Gaea-C6, and container
After the recent Gaea-C5 OS upgrade, gsi-monitor fails to build.
This issues corrects Gaea-C5 build, adds Gaea-C6 build capability (following [PR2448](https://github.com/ufs-community/ufs-weather-model/pull/2448)), and adds containerized build capability.

Refs NOAA-EMC/global-workflow [#3011](https://github.com/NOAA-EMC/global-workflow/issues/3011)
Refs NOAA-EMC/global-workflow [#3025](https://github.com/NOAA-EMC/global-workflow/issues/3025)

### PR DESCRIPTION
**Pull request by DavidBurrows-NCO**
After the recent Gaea-C5 OS upgrade, gsi-monitor fails to build.
This issues corrects Gaea-C5 build, adds Gaea-C6 build capability (following the ufs-wx-model [PR2448](https://github.com/ufs-community/ufs-weather-model/pull/2448)), and adds containerized build capability.

Refs NOAA-EMC/global-workflow [3011](https://github.com/NOAA-EMC/global-workflow/issues/3011)
Refs NOAA-EMC/global-workflow [3025](https://github.com/NOAA-EMC/global-workflow/issues/3025)
Closes #145

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
Who has review/merge permission here? @EdwardSafford-NOAA , others? @EdwardSafford-NOAA if so, can you review?

**Review by EdwardSafford-NOAA — APPROVED** [review]
Looks OK to me.

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA I do have review/merge access to this repo.  I don't have access to gaea* so I can't test the build but I'll take it on faith that it works.  I'm good with merging now unless you want a second set of eyes on this.

**Comment by CoryMartin-NOAA** [comment]
no I think it's fine I just saw that @DavidBurrows-NCO had several PRs open and I was doing my part to try to shepherd them along

**Comment by DavidBurrows-NCO** [comment]
Thanks you @CoryMartin-NOAA @EdwardSafford-NOAA

**Pull request merged**
