### PR TITLE
Correct use of data_chan.bifix array in radmon_angle.x executable.

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
See issue #33 for full description of problem.  

Changes build correctly on wcoss2, hera, and orion.  

Tested using global-workflow running the RadMon via the gdasvrfy job step with necessary data (radstat and abias files) staged in `$comrot`.

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
The revised code sets `cor_fixang(1)` to be the sum of `bifix(1:4)`.   `cor_fixang(2)` is the sum of the square of the sum of `bifix(1:4)`.   Issue #33 states that this is the correct assignment.    Thus, PR #35 does what Issue #33 says should be done.    

Has the revised code been compiled, executed, and results checked to confirm that the contents of `cor_fixang(1)` and `cor_fixang(2)` are correct?   I can approve given this confirmation.

**Comment by EdwardSafford-NOAA** [comment]
@RussTreadon-NOAA The changes have been compiled on wcoss2, hera, and orion.  They build without error.  The automated ci checks also confirm this.

I ran the RadMon using the vrfy job step in global_workflow.  The dumped values of cor_fixang(1:2) match the sum and sum-squared values of bifix(1:4).  Before these changes cor_fixang(1:2) were zero valued.

**Comment by RussTreadon-NOAA** [comment]
Thank you @EdwardSafford-NOAA for running the revised code and confirming that it behaves as expected.

**Review by RussTreadon-NOAA — APPROVED** [review]
Approve given confirmation that updated code yields correct results.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Pull request merged**
